# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Serial.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AithinkerSerial(object):
    def setupUi(self, AithinkerSerial):
        AithinkerSerial.setObjectName("AithinkerSerial")
        AithinkerSerial.resize(829, 726)
        self.centralwidget = MineWidget(AithinkerSerial)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowserShow = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowserShow.setStyleSheet("font: 10pt \"Consolas\";")
        self.textBrowserShow.setObjectName("textBrowserShow")
        self.horizontalLayout.addWidget(self.textBrowserShow)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 2, -1, -1)
        self.formLayout.setSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_port = MyQComBox(self.groupBox_3)
        self.comboBox_port.setEnabled(True)
        self.comboBox_port.setEditable(False)
        self.comboBox_port.setObjectName("comboBox_port")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_port)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_baud = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_baud.setEnabled(True)
        self.comboBox_baud.setEditable(True)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_baud)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_Bit = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_Bit.setObjectName("comboBox_Bit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_Bit)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_check = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_check.setObjectName("comboBox_check")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_check)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_stop = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_stop.setObjectName("comboBox_stop")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_stop)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bt_open_off_port = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_open_off_port.sizePolicy().hasHeightForWidth())
        self.bt_open_off_port.setSizePolicy(sizePolicy)
        self.bt_open_off_port.setObjectName("bt_open_off_port")
        self.horizontalLayout_5.addWidget(self.bt_open_off_port)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btSaveLog = QtWidgets.QPushButton(self.groupBox_4)
        self.btSaveLog.setObjectName("btSaveLog")
        self.verticalLayout.addWidget(self.btSaveLog)
        self.btClearLog = QtWidgets.QPushButton(self.groupBox_4)
        self.btClearLog.setObjectName("btClearLog")
        self.verticalLayout.addWidget(self.btClearLog)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_show_add_ctrl = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_show_add_ctrl.setObjectName("checkBox_show_add_ctrl")
        self.verticalLayout_2.addWidget(self.checkBox_show_add_ctrl)
        self.checkBox_show_hex = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_show_hex.setObjectName("checkBox_show_hex")
        self.verticalLayout_2.addWidget(self.checkBox_show_hex)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_rts = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_rts.setWhatsThis("")
        self.checkBox_rts.setChecked(True)
        self.checkBox_rts.setObjectName("checkBox_rts")
        self.verticalLayout_3.addWidget(self.checkBox_rts)
        self.checkBox_dtr = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_dtr.setObjectName("checkBox_dtr")
        self.verticalLayout_3.addWidget(self.checkBox_dtr)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_send_hex = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_send_hex.setObjectName("checkBox_send_hex")
        self.horizontalLayout_3.addWidget(self.checkBox_send_hex)
        self.checkBox_send_space_ctrl = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_send_space_ctrl.setObjectName("checkBox_send_space_ctrl")
        self.horizontalLayout_3.addWidget(self.checkBox_send_space_ctrl)
        self.checkBox_timer_send = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_timer_send.setObjectName("checkBox_timer_send")
        self.horizontalLayout_3.addWidget(self.checkBox_timer_send)
        self.lineEdit_ms_send = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ms_send.sizePolicy().hasHeightForWidth())
        self.lineEdit_ms_send.setSizePolicy(sizePolicy)
        self.lineEdit_ms_send.setObjectName("lineEdit_ms_send")
        self.horizontalLayout_3.addWidget(self.lineEdit_ms_send, 0, QtCore.Qt.AlignRight)
        self.label_ms = QtWidgets.QLabel(self.groupBox_6)
        self.label_ms.setObjectName("label_ms")
        self.horizontalLayout_3.addWidget(self.label_ms)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_send_data = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_send_data.setObjectName("bt_send_data")
        self.horizontalLayout_4.addWidget(self.bt_send_data)
        self.lineEdit_send_data = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_send_data.sizePolicy().hasHeightForWidth())
        self.lineEdit_send_data.setSizePolicy(sizePolicy)
        self.lineEdit_send_data.setObjectName("lineEdit_send_data")
        self.horizontalLayout_4.addWidget(self.lineEdit_send_data)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 6)
        self.verticalLayout_5.addWidget(self.groupBox_2)

        self.retranslateUi(AithinkerSerial)
        QtCore.QMetaObject.connectSlotsByName(AithinkerSerial)

    def retranslateUi(self, AithinkerSerial):
        _translate = QtCore.QCoreApplication.translate
        AithinkerSerial.setWindowTitle(_translate("AithinkerSerial", "半颗心脏 -- 串口调试助手 V1.0"))
        self.groupBox.setTitle(_translate("AithinkerSerial", "接收区（按F5清空接收区）"))
        self.label.setText(_translate("AithinkerSerial", "端口号"))
        self.label_2.setText(_translate("AithinkerSerial", "波特率"))
        self.label_3.setText(_translate("AithinkerSerial", "数据位"))
        self.label_4.setText(_translate("AithinkerSerial", "校验位"))
        self.label_5.setText(_translate("AithinkerSerial", "停止位"))
        self.bt_open_off_port.setText(_translate("AithinkerSerial", "打开串口"))
        self.btSaveLog.setText(_translate("AithinkerSerial", "保存接收"))
        self.btClearLog.setText(_translate("AithinkerSerial", "清空接收"))
        self.checkBox_show_add_ctrl.setText(_translate("AithinkerSerial", "自动换行"))
        self.checkBox_show_hex.setText(_translate("AithinkerSerial", "HEX显示"))
        self.checkBox_rts.setText(_translate("AithinkerSerial", "RTS"))
        self.checkBox_dtr.setText(_translate("AithinkerSerial", "DTR"))
        self.checkBox_send_hex.setText(_translate("AithinkerSerial", "HEX发送"))
        self.checkBox_send_space_ctrl.setText(_translate("AithinkerSerial", "发送新行"))
        self.checkBox_timer_send.setText(_translate("AithinkerSerial", "定时发送"))
        self.lineEdit_ms_send.setText(_translate("AithinkerSerial", "1000"))
        self.label_ms.setText(_translate("AithinkerSerial", "毫秒/次"))
        self.bt_send_data.setText(_translate("AithinkerSerial", "发送"))
from widget.MineWidget import MineWidget
from widget.MyQComBox import MyQComBox
